<a href="https://colab.research.google.com/github/ykro/ML-SP1-2021/blob/main/L1N3_Intro_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np.random.rand(5)

array([0.00128201, 0.40548994, 0.96490626, 0.88288738, 0.98391338])

In [3]:
np.random?

In [4]:
lst = list(range(10))
lst

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
arry = np.array(lst)
arry

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.argmax(arry), np.argmin(arry)

(9, 0)

In [11]:
print(arry[:3])
print(arry[3:])
print(arry[3:5])

[0 1 2]
[3 4 5 6 7 8 9]
[3 4]


In [12]:
arry.shape

(10,)

In [16]:
arry_rows = np.reshape(arry, (5,2))
print(arry_rows.shape) 
print(arry_rows)

(5, 2)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [18]:
arry_cols = np.reshape(arry, (2,5))
print(arry_cols.shape) 
print(arry_cols)

(2, 5)
[[0 1 2 3 4]
 [5 6 7 8 9]]
